version: '3'
services:
  app:
    build: .
    container_name: nginx-app
    restart: always
    expose:
      - "5000"
  
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
